# Generated by Django 2.2.5 on 2020-10-12 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='visuals/assets')),
                ('mean', models.IntegerField()),
                ('mode', models.IntegerField()),
            ],
        ),
    ]
