# Generated by Django 2.2.5 on 2020-10-12 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Visuals', '0002_country_median'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='mean',
        ),
        migrations.RemoveField(
            model_name='country',
            name='median',
        ),
        migrations.RemoveField(
            model_name='country',
            name='mode',
        ),
    ]
